name: Validation

on:
  workflow_run:
    workflows: ["PreValidation"]
    types:
      - completed

jobs:
  Validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Validation
      run: echo "Running Validation"