name: PostValidation

on:
  workflow_run:
    workflows: ["Validation"]
    types:
      - completed

jobs:
  PostValidation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run PostValidation
      run: echo "Running PostValidation"